/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ChessUnbound.view.HomePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.home',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'ChessUnbound'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom'
            },
            {
                xtype: 'button',
                docked: 'top',
                height: '45px',
                itemId: 'newGameBtn',
                iconCls: 'add',
                iconMask: true,
                text: 'New Game'
            },
            {
                xtype: 'list',
                itemTpl: [
                    '<div>Game {name}</div>'
                ],
                store: 'gamestore'
            }
        ],
        listeners: [
            {
                fn: 'onNewGameBtnTap',
                event: 'tap',
                delegate: '#newGameBtn'
            }
        ]
    },

    onNewGameBtnTap: function(button, e, eOpts) {
        this.fireEvent("newGameCommand", this);
    }

});