/*
 * File: app/view/Home.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ChessToGo.view.Home', {
    extend: 'Ext.Panel',
    alias: 'widget.home',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Home'
            },
            {
                xtype: 'newgamebutton',
                itemId: 'newgamebutton',
                ui: 'action',
                iconCls: 'star',
                text: 'New Game'
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#newgamebutton'
            }
        ]
    },

    onMybuttonTap: function(button, e, eOpts) {
        this.fireEvent("newGameCommand");
        console.log("NewGameCommand");
    }

});