/*
 * File: app/controller/HomeController.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ChessToGo.controller.HomeController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            home: {
                autoCreate: true,
                selector: 'home',
                xtype: 'home'
            },
            gameEditor: {
                autoCreate: true,
                selector: 'gameeditor',
                xtype: 'gameeditor'
            }
        },

        control: {
            "panel": {
                newGameCommand: 'onNewGameCommand'
            }
        }
    },

    onNewGameCommand: function(panel) {
        console.log("onNewGameCommand");
        var gameEditor = this.getGameEditor();
        Ext.Viewport.animateActiveItem(gameEditor, ChessToGo.app.slideLeft());
    }

});